### ISSUE TITLE
performance reports broken due to bokeh 3.0

### ISSUE THREAD

**Issue by dchudz** [coiled/coiled-runtime#534] opened 2022-11-17 18:36 UTC
I think this is fixed in latest distributed, but `coiled-runtime` uses an older distributed, and coiled-runtime 0.1.0 does not pin bokeh.

```
Last login: Thu Nov 17 13:18:33 on ttys005
bye
cond(base)  /Users/davidchudzicki $
conda activate coiled-runtime
(coiled-runtime)  /Users/davidchudzicki $
ipython
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from dask.distributed import Client, performance_report

In [2]: client = Client()
/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 58077 instead
  warnings.warn(

In [3]: with performance_report(filename="dask-report.html"):
   ...:     client.submit(lambda x: x, 1)
   ...:
2022-11-17 13:34:11,917 - distributed.core - ERROR - Exception while handling op performance_report
Traceback (most recent call last):
  File "/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/core.py", line 597, in handle_comm
    result = await result
  File "/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/scheduler.py", line 6754, in performance_report
    from distributed.dashboard.components.scheduler import task_stream_figure
  File "/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/dashboard/components/scheduler.py", line 13, in <module>
    from bokeh.models import (
ImportError: cannot import name 'Panel' from 'bokeh.models' (/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/bokeh/models/__init__.py)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [3], line 1
----> 1 with performance_report(filename="dask-report.html"):
      2     client.submit(lambda x: x, 1)

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/client.py:5255, in performance_report.__exit__(self, exc_type, exc_value, traceback)
   5253 client = get_client()
   5254 code = client._get_computation_code(self._stacklevel + 1)
-> 5255 client.sync(self.__aexit__, exc_type, exc_value, traceback, code=code)

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/utils.py:320, in SyncMethodMixin.sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    318     return future
    319 else:
--> 320     return sync(
    321         self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    322     )

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/utils.py:387, in sync(loop, func, callback_timeout, *args, **kwargs)
    385 if error:
    386     typ, exc, tb = error
--> 387     raise exc.with_traceback(tb)
    388 else:
    389     return result

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/utils.py:360, in sync.<locals>.f()
    358         future = asyncio.wait_for(future, callback_timeout)
    359     future = asyncio.ensure_future(future)
--> 360     result = yield future
    361 except Exception:
    362     error = sys.exc_info()

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/tornado/gen.py:762, in Runner.run(self)
    759 exc_info = None
    761 try:
--> 762     value = future.result()
    763 except Exception:
    764     exc_info = sys.exc_info()

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/client.py:5243, in performance_report.__aexit__(self, exc_type, exc_value, traceback, code)
   5241 if code is None:
   5242     code = client._get_computation_code(self._stacklevel + 1)
-> 5243 data = await client.scheduler.performance_report(
   5244     start=self.start, last_count=self.last_count, code=code, mode=self.mode
   5245 )
   5246 with open(self.filename, "w") as f:
   5247     f.write(data)

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/core.py:984, in PooledRPCCall.__getattr__.<locals>.send_recv_from_rpc(**kwargs)
    982 prev_name, comm.name = comm.name, "ConnectionPool." + key
    983 try:
--> 984     return await send_recv(comm=comm, op=key, **kwargs)
    985 finally:
    986     self.pool.reuse(self.addr, comm)

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/core.py:772, in send_recv(comm, reply, serializers, deserializers, **kwargs)
    770 if comm.deserialize:
    771     typ, exc, tb = clean_exception(**response)
--> 772     raise exc.with_traceback(tb)
    773 else:
    774     raise Exception(response["exception_text"])

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/core.py:597, in handle_comm()
    595     self._ongoing_coroutines.add(result)
    596     result.add_done_callback(self._ongoing_coroutines.remove)
--> 597     result = await result
    598 elif inspect.isawaitable(result):
    599     raise RuntimeError(
    600         f"Comm handler returned unknown awaitable. Expected coroutine, instead got {type(result)}"
    601     )

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/scheduler.py:6754, in performance_report()
   6751 for k in sorted(timespent.keys()):
   6752     tasks_timings += f"\n<li> {k} time: {format_time(timespent[k])} </li>"
-> 6754 from distributed.dashboard.components.scheduler import task_stream_figure
   6755 from distributed.diagnostics.task_stream import rectangles
   6757 rects = rectangles(task_stream)

File /opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/distributed/dashboard/components/scheduler.py:13
     11 from bokeh.io import curdoc
     12 from bokeh.layouts import column, row
---> 13 from bokeh.models import (
     14     AdaptiveTicker,
     15     Arrow,
     16     BasicTicker,
     17     BoxSelectTool,
     18     BoxZoomTool,
     19     CDSView,
     20     ColorBar,
     21     ColumnDataSource,
     22     CustomJSHover,
     23     DataRange1d,
     24     FactorRange,
     25     GroupFilter,
     26     HoverTool,
     27     NumberFormatter,
     28     NumeralTickFormatter,
     29     OpenURL,
     30     Panel,
     31     PanTool,
     32     Range1d,
     33     ResetTool,
     34     Tabs,
     35     TapTool,
     36     Title,
     37     VeeHead,
     38     WheelZoomTool,
     39     value,
     40 )
     41 from bokeh.models.widgets import DataTable, TableColumn
     42 from bokeh.models.widgets.markups import Div

ImportError: cannot import name 'Panel' from 'bokeh.models' (/opt/miniconda3/envs/coiled-runtime/lib/python3.10/site-packages/bokeh/models/__init__.py)

In [4]:
```

```
conda list
# packages in environment at /opt/miniconda3/envs/coiled-runtime:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
abseil-cpp                20211102.0           h6b3803e_1    conda-forge
aiobotocore               2.3.4              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.3           py310h8e9501a_1    conda-forge
aioitertools              0.11.0             pyhd8ed1ab_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h8e9501a_3    conda-forge
arrow-cpp                 8.0.0           py310h460715f_3_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.1.0              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
aws-c-cal                 0.5.11               h4530763_0    conda-forge
aws-c-common              0.6.2                h3422bc3_0    conda-forge
aws-c-event-stream        0.2.7               h9972306_13    conda-forge
aws-c-io                  0.10.5               hea86ef8_0    conda-forge
aws-checksums             0.1.11               h487e1a8_7    conda-forge
aws-sdk-cpp               1.8.186              h392f50b_4    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backoff                   1.11.1             pyhd8ed1ab_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blinker                   1.5                pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               hd414afc_3    conda-forge
bokeh                     3.0.2                    pypi_0    pypi
boto3                     1.21.21            pyhd8ed1ab_0    conda-forge
botocore                  1.24.21            pyhd8ed1ab_1    conda-forge
brotlipy                  0.7.0           py310h8e9501a_1005    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.9.24            h4653dfc_0    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2399d43_2    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
coiled                    0.2.41             pyhd8ed1ab_0    conda-forge
coiled-runtime            0.1.0                hd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
contourpy                 1.0.6                    pypi_0    pypi
cryptography              38.0.3          py310h4fe9c50_0    conda-forge
cytoolz                   0.12.0          py310h8e9501a_1    conda-forge
dask                      2022.6.0           pyhd8ed1ab_0    conda-forge
dask-core                 2022.6.0           pyhd8ed1ab_0    conda-forge
dask-glm                  0.2.0                      py_1    conda-forge
dask-labextension         5.2.0              pyhd8ed1ab_0    conda-forge
dask-ml                   2022.5.27          pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.6.3           py310h0f1eb42_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2022.6.0           pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hd633e50_0    conda-forge
frozenlist                1.3.1           py310h8e9501a_1    conda-forge
fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2             pyhd8ed1ab_6    conda-forge
gcsfs                     2022.5.0           pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
google-api-core           2.10.1             pyhd8ed1ab_0    conda-forge
google-auth               2.14.0             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      0.7.1              pyhd8ed1ab_0    conda-forge
google-cloud-core         2.3.2              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.5.0              pyh6c4a22f_0    conda-forge
google-crc32c             1.1.2           py310he58995c_4    conda-forge
google-resumable-media    2.4.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.56.4          py310hbe9552e_1    conda-forge
grpc-cpp                  1.46.3               h6666856_1    conda-forge
grpcio                    1.46.3          py310hfea1ced_1    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
importlib_metadata        5.0.0                hd8ed1ab_1    conda-forge
importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
ipycytoscape              1.3.3              pyhd8ed1ab_1    conda-forge
ipykernel                 6.17.0             pyh736e0ef_0    conda-forge
ipython                   8.6.0              pyhd1c38e8_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   he4db4b2_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsondiff                  2.0.0              pyhd8ed1ab_0    conda-forge
jsonschema                4.17.0             pyhd8ed1ab_0    conda-forge
jupyter-server-proxy      3.2.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.2          py310hbe9552e_0    conda-forge
jupyter_server            1.21.0             pyhd8ed1ab_0    conda-forge
jupyterlab                3.4.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.16.2             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
krb5                      1.19.3               hf9b2bbe_0    conda-forge
lcms2                     2.14                 h8193b64_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   7.86.0               hd538317_1    conda-forge
libcxx                    14.0.6               h2692d47_0    conda-forge
libdeflate                1.14                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.10               hbae9a57_4    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
libgoogle-cloud           1.40.2               h5539620_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libllvm11                 11.1.0               hfa12f05_5    conda-forge
libnghttp2                1.47.0               h232270b_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libpng                    1.6.38               h76d750c_0    conda-forge
libprotobuf               3.20.1               hb5ab8b9_4    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.39.4               h76d750c_0    conda-forge
libssh2                   1.10.0               hb80f160_3    conda-forge
libthrift                 0.16.0               h1a74c4f_2    conda-forge
libtiff                   4.4.0                hfa0b094_4    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libwebp-base              1.2.4                h57fd34a_0    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxgboost                1.6.1            cpu_h7e51313_1    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
llvmlite                  0.38.1          py310hbf292a2_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.0           py310ha6df754_3    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
markupsafe                2.1.1           py310h8e9501a_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3           py310hea002bf_1    conda-forge
multidict                 6.0.2           py310h8e9501a_2    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.3              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
notebook                  6.5.2              pyha770c72_0    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
numba                     0.55.1          py310ha67b2a8_1    conda-forge
numcodecs                 0.10.2          py310hc6dc59f_0    conda-forge
numpy                     1.21.6          py310h2e04ed8_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                h5d4e404_1    conda-forge
openssl                   1.1.1s               h03a7124_0    conda-forge
orc                       1.7.5                h96f55be_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2           py310ha6a5cd6_2    conda-forge
pandoc                    2.19.2               hce30654_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h9337a76_3    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prometheus_client         0.15.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
protobuf                  3.20.1          py310hb07a4bc_0    conda-forge
psutil                    5.9.3           py310h8e9501a_1    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-xgboost                1.6.1           cpu_py310ha244a38_1    conda-forge
pyarrow                   8.0.0           py310h2302aac_3_cpu    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.6.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.2          py310h8e9501a_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.6          hbce4517_0_cpython    conda-forge
python-blosc              1.10.2          py310hdead3df_2    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.6             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h8e9501a_5    conda-forge
pyzmq                     24.0.1          py310hc407298_1    conda-forge
re2                       2022.04.01           h6b3803e_0    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rich                      12.6.0             pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
s3fs                      2022.5.0           pyhd8ed1ab_0    conda-forge
s3transfer                0.5.2              pyhd8ed1ab_0    conda-forge
scikit-learn              1.1.1           py310h16bc539_0    conda-forge
scipy                     1.9.3           py310ha0d8a01_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
simpervisor               0.4                pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h17c5cce_2    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spectate                  1.0.1              pyhd8ed1ab_0    conda-forge
stack_data                0.6.0              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.0             pyhd1c38e8_0    conda-forge
textual                   0.1.18             pyhd8ed1ab_1    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1             py310hf8d0d8f_3    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022f                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
wrapt                     1.14.1          py310h8e9501a_1    conda-forge
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xgboost                   1.6.1           cpu_py310he362541_1    conda-forge
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2022.9.0                 pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.8.1           py310h8e9501a_0    conda-forge
zarr                      2.11.3             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```

**Comment by jrbourbeau** [comment] 2022-11-17 18:38
Thanks @dchudz -- closing as a duplicate of https://github.com/coiled/coiled-runtime/issues/520. @ncclementi is pushing out a `coiled-runtime=0.1.1` patch release to fix this

**Closed by jrbourbeau** 2022-11-17 18:38 UTC
